name: Franco Cedillo personal page on GitHub

url: http://adagio.github.io

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
      published: true

exclude: [ config.rb, Gemfile, params.json, README.md ]