name: Franco Cedillo personal page on GitHub

markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

url: http://adagio.github.io
